### ISSUE TITLE
New EDMC version - 5.8.0-rc3

### ISSUE THREAD

**Issue by Athanasius** [flathub/io.edcd.EDMarketConnector#12]
This is only a Release Candidate right now, but if no issues are reported with it before Friday I'll release it as the full 5.8.0 then.

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.8.0-rc1

**Comment by Athanasius** [comment]
Make that 5.8.0-rc3, as we found some issues with building of the windows program/installer.  Not that it would affect this... but might as well use the `Release/5.8.0-rc3` tag if testing for a new flathub release.

**Comment by dvdmuckle** [comment]
Looks like 5.8.0 is properly out. I added an auto version checker to my PR #11, this will use the same auto version bump tool that is currently looking at the Python modules.
