### ISSUE TITLE
Fix version in `About` showing `+UNKNOWN`

### ISSUE THREAD

**Issue by der-eismann** [flathub/io.edcd.EDMarketConnector#13]
There's no git, so the version shows as `+UNKNOWN`. But this is a release, we should show it correctly.

![Bildschirmfoto vom 2023-01-20 21-18-44](https://user-images.githubusercontent.com/10406217/213798111-a4dad3de-414e-4d66-8796-67455fbcbcbe.png)

**Comment by dvdmuckle** [comment]
I found the chunk responsible for generating this, it might be easier to address it there than to add git as a dependency. I'm going to check out what the behavior is on the Windows install. It might be the case that this behavior is also on the Windows installer version, which means fixing this in the code would fix it for both Linux and Windows.

**Comment by dvdmuckle** [comment]
Ah, the Windows version is running "frozen" and thus this chunk of code uses the .gitversion file included in the frozen app state. So the Windows version does include the hash.

**Comment by dvdmuckle** [comment]
This is kinda sorta an app issue so to start the discussion on that end, I opened up https://github.com/EDCD/EDMarketConnector/issues/1827

**Comment by der-eismann** [comment]
Fixed by upstream in https://github.com/EDCD/EDMarketConnector/pull/2118, thanks @dvdmuckle!
