### ISSUE TITLE
Flatpak version of EDMC Out of Date (5.8.1 vs. 5.9.5)

### ISSUE THREAD

**Issue by TheDaviot** [flathub/io.edcd.EDMarketConnector#29]
As noted, the current standalone version of EDMC is up to 5.9.5, which makes several fixes as well as removes EDDB integration due to that website shutting down.

Can an updated build of the Flatpak be pushed through to the Flathub site?

**Comment by der-eismann** [comment]
I tried to update it today, but while testing I hit https://github.com/EDCD/EDMarketConnector/issues/2077, so it'll need to wait until I figured this out.

**Comment by der-eismann** [comment]
Okay, turns out that this is actually just a configuration issue, as I needed to choose a different station provider. Will update the Flatpak in time.

**Comment by der-eismann** [comment]
Fixed with #30
